### ISSUE TITLE
Error after deleting the active theme

### ISSUE THREAD

**Issue by laulaz** [plone/plone.app.theming#101]
In the `@@theming-controlpanel`, we should :
- warn the user when he deletes the active theme
- or prevent the user to delete the active theme
- or deactivate the theme when the user deletes the active theme

Otherwise, we get errors like :
```
2016-04-18 16:42:20 ERROR plone.subrequest Error handling subrequest to /++theme++mytheme/rules.xml
Traceback (most recent call last):
  File "/Users/user/.buildout/eggs/plone.subrequest-1.6.11-py2.6.egg/plone/subrequest/__init__.py", line 137, in subrequest
    traversed = request.traverse(path)
  File "/Users/user/.buildout/eggs/Zope2-2.13.24-py2.6.egg/ZPublisher/BaseRequest.py", line 508, in traverse
    subobject = self.traverseName(object, entry_name)
  File "/Users/user/.buildout/eggs/Zope2-2.13.24-py2.6.egg/ZPublisher/BaseRequest.py", line 332, in traverseName
    ob2 = namespaceLookup(ns, nm, ob, self)
  File "/Users/user/.buildout/eggs/zope.traversing-3.13.2-py2.6.egg/zope/traversing/namespace.py", line 112, in namespaceLookup
    return traverser.traverse(name, ())
  File "/Users/user/.buildout/eggs/plone.resource-1.0.5-py2.6.egg/plone/resource/traversal.py", line 27, in traverse
    raise NotFound
NotFound
2016-04-18 16:42:20 ERROR plone.app.theming Couldn't resolve /++theme++mytheme/rules.xml
2016-04-18 16:42:20 ERROR plone.transformchain Unexpected error whilst trying to apply transform chain
Traceback (most recent call last):
  File "/Users/user/.buildout/eggs/plone.transformchain-1.1.0-py2.6.egg/plone/transformchain/transformer.py", line 43, in __call__
    newResult = handler.transformIterable(result, encoding)
  File "/Users/user/.buildout/eggs/plone.app.theming-1.1.7-py2.6.egg/plone/app/theming/transform.py", line 170, in transformIterable
    transform = self.setupTransform(runtrace=runtrace)
  File "/Users/user/.buildout/eggs/plone.app.theming-1.1.7-py2.6.egg/plone/app/theming/transform.py", line 108, in setupTransform
    transform = compileThemeTransform(rules, absolutePrefix, readNetwork, parameterExpressions, runtrace=runtrace)
  File "/Users/user/.buildout/eggs/plone.app.theming-1.1.7-py2.6.egg/plone/app/theming/utils.py", line 602, in compileThemeTransform
    runtrace=runtrace,
  File "/Users/user/.buildout/eggs/diazo-1.1.3-py2.6.egg/diazo/compiler.py", line 113, in compile_theme
    read_network=read_network,
  File "/Users/user/.buildout/eggs/diazo-1.1.3-py2.6.egg/diazo/rules.py", line 210, in process_rules
    rules_doc = etree.parse(rules, parser=rules_parser)
  File "lxml.etree.pyx", line 2957, in lxml.etree.parse (src/lxml/lxml.etree.c:56299)
  File "parser.pxi", line 1526, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:82331)
  File "parser.pxi", line 1555, in lxml.etree._parseDocumentFromURL (src/lxml/lxml.etree.c:82624)
  File "parser.pxi", line 1455, in lxml.etree._parseDocFromFile (src/lxml/lxml.etree.c:81663)
  File "parser.pxi", line 1002, in lxml.etree._BaseParser._parseDocFromFile (src/lxml/lxml.etree.c:78623)
  File "parser.pxi", line 569, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:74567)
  File "parser.pxi", line 650, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:75458)
  File "parser.pxi", line 588, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:74760)
IOError: Error reading file '/++theme++mytheme/rules.xml': failed to load external entity "/++theme++mytheme/rules.xml"

```

**Comment by khanstark** [comment]
there is already a warning modal box that pops up on trying to delete active theme ...
![fish](https://cloud.githubusercontent.com/assets/17498833/14675789/446c4976-0728-11e6-909d-299725414a14.png)

Or are u implying something else?

**Comment by laulaz** [comment]
This message doesn't tell the user that the theme is currently active :wink:
