### ISSUE TITLE
Bug (theme not applied) if we have a public section in a private Plone site

### ISSUE THREAD

**Issue by laulaz** [plone/plone.app.theming#142]
If we have a private Plone site (ex: intranet) but with a public content somewhere below a `INavigationRoot` (ex: a page with terms and conditions), when accessing this page, we get a traceback :
```
2018-04-30 20:38:45 ERROR plone.subrequest Error handling subrequest to /++theme++my.theme/rules.xml
Traceback (most recent call last):
  File "eggs/plone.subrequest-1.8-py2.7.egg/plone/subrequest/__init__.py", line 144, in subrequest
    traversed = request.traverse(path)
  File "eggs/Zope2-2.13.26-py2.7.egg/ZPublisher/BaseRequest.py", line 623, in traverse
    response.unauthorized()
  File "eggs/Zope2-2.13.26-py2.7.egg/ZPublisher/HTTPResponse.py", line 756, in unauthorized
    raise Unauthorized, m
Unauthorized: You are not authorized to access this resource.
2018-04-30 20:38:45 ERROR plone.app.theming Couldn't resolve /++theme++my.theme/rules.xml
2018-04-30 20:38:45 ERROR plone.transformchain Unexpected error whilst trying to apply transform chain
Traceback (most recent call last):
  File "eggs/plone.transformchain-1.2.0-py2.7.egg/plone/transformchain/transformer.py", line 49, in __call__
    newResult = handler.transformIterable(result, encoding)
  File "eggs/plone.app.theming-1.3.6-py2.7.egg/plone/app/theming/transform.py", line 153, in transformIterable
    transform = self.setupTransform(runtrace=runtrace)
  File "eggs/plone.app.theming-1.3.6-py2.7.egg/plone/app/theming/transform.py", line 94, in setupTransform
    runtrace=runtrace
  File "eggs/plone.app.theming-1.3.6-py2.7.egg/plone/app/theming/utils.py", line 612, in compileThemeTransform
    runtrace=runtrace,
  File "eggs/diazo-1.2.5-py2.7.egg/diazo/compiler.py", line 113, in compile_theme
    read_network=read_network,
  File "eggs/diazo-1.2.5-py2.7.egg/diazo/rules.py", line 223, in process_rules
    rules_doc = etree.parse(rules, parser=rules_parser)
  File "src/lxml/lxml.etree.pyx", line 3427, in lxml.etree.parse (src/lxml/lxml.etree.c:85131)
  File "src/lxml/parser.pxi", line 1782, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:124005)
  File "src/lxml/parser.pxi", line 1808, in lxml.etree._parseDocumentFromURL (src/lxml/lxml.etree.c:124374)
  File "src/lxml/parser.pxi", line 1712, in lxml.etree._parseDocFromFile (src/lxml/lxml.etree.c:123169)
  File "src/lxml/parser.pxi", line 1115, in lxml.etree._BaseParser._parseDocFromFile (src/lxml/lxml.etree.c:117533)
  File "src/lxml/parser.pxi", line 573, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:110510)
  File "src/lxml/parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:112276)
  File "src/lxml/parser.pxi", line 611, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:111078)
IOError: Error reading file '/++theme++my.theme/rules.xml': failed to load external entity "/++theme++my.theme/rules.xml"
```
so the theme do not apply.

In my simple usecase, the navigation root is a language folder (multilingual site) and the public content is a document.

Is there a reason why we make a subrequest (in `utils.InternalResolver.resolve`) on `navigation_root` and not on `portal` directly ?
Because that would fix the bug.

**Comment by yurj** [comment]
I've a similar problem with a multilang site, see https://github.com/plone/plone.app.layout/issues/279

**Comment by pbauer** [comment]
I have exactly the same issue and did some further investigation (Using vanilla Plone Classic UI 6.0.8 and 6.0.9)

See also https://community.plone.org/t/error-in-theme-barceloneta/13426/2 for a mention of that problem.

To reproduce:

* Make the type Folde the Navigation-Root (enable the behavior plone.navigationroot in http://localhost:8080/Plone/dexterity-types/Folder/@@behaviors)
* Create a folder http://localhost:8080/Plone/folder and keep that private
* In that folder create a page http://localhost:8080/Plone/folder/page and publish it
* Create a folder http://localhost:8080/Plone/published-folder and publish it
* In that published folder create a page http://localhost:8080/Plone/published-folder/private-page and keep it private
* Create a new user "tester" without additional groups 
* Login as that user (e.g. in a different browser)

I also added a logger in `plone/subrequest/__init__.py` before the line `traversed = request.traverse(path)` to log the current user. You don't need that unless you don't trust my findings below.

Now you can investigate a couple of things:

**Case 1: private navroot, public page** 
Open http://localhost:8080/Plone/folder/page

Result: 

* The content of the page renders but the theme is broken
* In `plone/subrequest/__init__.py` the traversal to `/Plone/folder/++theme++barceloneta/rules.xml` and `/Plone/folder/++theme++barceloneta/index.html` (in `traversed = request.traverse(path)`) happens as the user "tester". 
* The traversal as user "tester" yields these tracebacks:

```
2023-12-21 12:47:04,087 ERROR   [plone.subrequest:163][waitress-0] Error handling subrequest to /++theme++barceloneta/rules.xml
Traceback (most recent call last):
  File "/Users/pbauer/.cache/buildout/eggs/cp311/plone.subrequest-2.0.4-py3.11.egg/plone/subrequest/__init__.py", line 146, in subrequest
    traversed = request.traverse(path)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pbauer/.cache/buildout/eggs/cp311/Zope-5.9-py3.11.egg/ZPublisher/BaseRequest.py", line 641, in traverse
    response.unauthorized()
  File "/Users/pbauer/.cache/buildout/eggs/cp311/Zope-5.9-py3.11.egg/ZPublisher/HTTPResponse.py", line 839, in unauthorized
    raise Unauthorized(m)
zExceptions.unauthorized.Unauthorized: You are not authorized to access this resource.
2023-12-21 12:47:04,154 ERROR   [plone.app.theming:184][waitress-0] Couldn't resolve /++theme++barceloneta/rules.xml
2023-12-21 12:47:04,154 ERROR   [plone.transformchain:60][waitress-0] Unexpected error whilst trying to apply transform chain
Traceback (most recent call last):
  File "/Users/pbauer/.cache/buildout/eggs/cp311/plone.transformchain-3.0.0-py3.11.egg/plone/transformchain/transformer.py", line 50, in __call__
    newResult = handler.transformIterable(result, encoding)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pbauer/.cache/buildout/eggs/cp311/plone.app.theming-5.0.6-py3.11.egg/plone/app/theming/transform.py", line 168, in transformIterable
    transform = self.setupTransform(runtrace=runtrace)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pbauer/.cache/buildout/eggs/cp311/plone.app.theming-5.0.6-py3.11.egg/plone/app/theming/transform.py", line 91, in setupTransform
    transform = compileThemeTransform(
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pbauer/.cache/buildout/eggs/cp311/plone.app.theming-5.0.6-py3.11.egg/plone/app/theming/utils.py", line 662, in compileThemeTransform
    compiledTheme = compile_theme(
                    ^^^^^^^^^^^^^^
  File "/Users/pbauer/.cache/buildout/eggs/cp311/diazo-1.5.0-py3.11.egg/diazo/compiler.py", line 129, in compile_theme
    rules_doc = process_rules(
                ^^^^^^^^^^^^^^
  File "/Users/pbauer/.cache/buildout/eggs/cp311/diazo-1.5.0-py3.11.egg/diazo/rules.py", line 293, in process_rules
    rules_doc = etree.parse(rules, parser=rules_parser)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src/lxml/etree.pyx", line 3541, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1879, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1905, in lxml.etree._parseDocumentFromURL
  File "src/lxml/parser.pxi", line 1808, in lxml.etree._parseDocFromFile
  File "src/lxml/parser.pxi", line 1180, in lxml.etree._BaseParser._parseDocFromFile
  File "src/lxml/parser.pxi", line 618, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 728, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 655, in lxml.etree._raiseParseError
OSError: Error reading file '/++theme++barceloneta/rules.xml': failed to load external entity "/++theme++barceloneta/rules.xml"
```


**Case 2: private navroot**
Open http://localhost:8080/Plone/folder

* You are redirected to http://localhost:8080/Plone/insufficient-privileges. The theme looks ok.
* In `plone.subrequest.subrequest` the first traversal to /Plone/folder/++theme++barceloneta/rules.xml (`traversed = request.traverse(path)`) happens as Anonymous. 
* During rendering of `insufficient-privileges` the same traversal is done as "tester".


**Case 3: theme-file in private navroot**
Open http://localhost:8080/Plone/folder/++theme++barceloneta/rules.xml

* Your are redirected to http://localhost:8080/Plone/insufficient-privileges
* In `plone.subrequest.subrequest` the first traversal to /Plone/folder/++theme++barceloneta/rules.xml (`traversed = request.traverse(path)`) happens as Anonymous. 
* During rendering of `insufficient-privileges` the same traversal is done as "tester".


**Case 4: public navroot**
Open http://localhost:8080/Plone/published-folder

* The Folder renders. The theme looks ok.
* In `plone.subrequest.subrequest` the traversal to /Plone/folder/++theme++barceloneta/rules.xml (`traversed = request.traverse(path)`) happens as "tester". 


**Case 5: public navroot, private page**
Open http://localhost:8080/Plone/published-folder/private-page

* You are redirected to http://localhost:8080/Plone/insufficient-privileges. The theme looks ok.
* In `plone.subrequest.subrequest` the first traversal to `/Plone/folder/++theme++barceloneta/rules.xml` (`traversed = request.traverse(path)`) happens as Anonymous. 
* During rendering of `insufficient-privileges` the same traversal is done as "tester".


**Now change `plone.app.theming.utils.InternalResolver.resolve` to use `root = portalState.portal()` instead of `root = portalState.navigation_root()` and try again:**

**Case 6: privat navroot, public page, rooted-theme**
Open http://localhost:8080/Plone/folder/page

* The page looks fine since the theme-files can be accessed now. 
* The traversal in `plone.subrequest.subrequest` (now to `/Plone/++theme++barceloneta/rules.xml`) still happens as Anonymous but returns the file.


**Case 7: public navroot, private page, rooted-theme** 
Open http://localhost:8080/Plone/published-folder/private-page

* You are redirected to http://localhost:8080/Plone/insufficient-privileges. The theme looks ok.
* In `plone.subrequest.subrequest` the first traversal to `/Plone/++theme++barceloneta/rules.xml` happens as Anonymous. 
* During rendering of `insufficient-privileges` the same traversal is done as "tester".



**My main questions**

* Why does the traversal to the theme-files happen as Anonymous in all cases except for 1 and 4? I could not find any reason why that is the case or where that actually happens. 
* Why does the `InternalResolver` use the navigation-root to access the theme-files. Is this because we might have different theme-files for different subsites?

**Comment by yurj** [comment]
In case 1, loading /++theme++barceloneta/rules.xml on the browser works? There's 2 problems:

1 why we want to load /Plone/folder/++theme++barceloneta/rules.xml? Here Diazo should load `<portal>/++theme++barceloneta/rules.xml`
2 why loading via traversal of `/Plone/folder/++theme++barceloneta/rules.xml` lead to an Unauthorized?

For 1, Diazo should always use portal as base, so adding a portal_url variable and using it could solve the problem. But what about Plone folder with nav root set as nav sites and main url pointing to it (subsites)? In that case portal_url does not exists, the folder has https://mysite.com/ as public url but the portal itself has not. That's why we use navroot in that case. So use portal url or navroot if portal_url is not available

for 2, there are special rules in traversing for ++ namespaces. Theme resources are always to be accessed from the portal_url root. They are even available in Zope root too (myserver:8080/++theme++barceloneta/rules.xml works) because they're not Plone specific.

Diazo is setting the theme, Diazo is searching for /++theme++barceloneta/rules.xml so Diazo must know what we want to do. For example, Barceloneta config is (`manifest.cfg` https://github.com/plone/plonetheme.barceloneta/blob/master/plonetheme/barceloneta/theme/manifest.cfg):

rules = /++theme++barceloneta/rules.xml

What is this first '/' about?

**Comment by pbauer** [comment]
@yurj: Yes, in Case 1 (private folder, public page) http://localhost:8080/Plone/++theme++barceloneta/rules.xml works
http://localhost:8080/Plone/folder/page/++theme++barceloneta/rules.xml also works, only 
http://localhost:8080/Plone/folder/++theme++barceloneta/rules.xml throws Unauthorized:

2023-12-25 11:13:57,492 DEBUG   [ImplPython:844][waitress-2] Unauthorized: Your user account does not have the required permission.  Access to 'rules.xml' of (FilesystemResourceDirectory object at barceloneta) denied. Your user account, tester, exists at /Plone/acl_users. Access requires Access_contents_information_Permission, granted to the following roles: ['Contributor', 'Editor', 'Manager', 'Owner', 'Reader', 'Site Administrator']. Your roles in this context are ['Authenticated', 'Member'].

I submitted a fix with https://github.com/plone/plone.app.theming/pull/232

The change does not break any tests which leads me to think that the reason for the initial change to use the navroot  in 
https://github.com/plone/plone.app.theming/commit/3e8d5956d8e65dceb8d78155a8cf88b5c0278215 (to supply the closest context found for 404 pages) is preserved.

For me that fixes the theme and the corresponding tracebacks in all cases. 
But it does **not** change the fact or answer the question why the initial traversal to the theme-files happen as Anonymous in all cases except for Case 1 and Case 4.

**Comment by yurj** [comment]
maybe @lrowe remember why? The 404 page should be as any other template page.

**Comment by pbauer** [comment]
See https://community.plone.org/t/why-are-users-anonymous-on-error-pages/18844/2
The reason seems to be that authentication only happens after successful traversal.
